"""
Cross-SDK parity: the Python SDK must produce byte-for-byte identical signed
output to the JS SDK.

The golden vector (tests/fixtures/js_parity_vector.json) is generated by the
*built JS SDK* — see js/scripts/gen-parity-vector.js. These tests re-sign the
same inputs with the same key at the same fixed timestamp and assert the
Python bytes + Ed25519 signatures match exactly, and that Python verifies the
JS-produced signatures. This is what guarantees notifications / key rotation /
views signed by either SDK are accepted by the same backend and renderer.

Run `node js/scripts/gen-parity-vector.js` to refresh after a JS signing change.
"""

import json
import os

import pytest

from yeriasdk import YeriaApp, YeriaAppConfig, Notification

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "js_parity_vector.json")


@pytest.fixture(scope="module")
def vector():
    with open(FIXTURE) as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def app(vector):
    return YeriaApp(
        YeriaAppConfig(
            app_id=vector["appId"],
            private_key=vector["privateKey"],
            public_key=vector["publicKey"],
        )
    )


def test_view_payload_bytes_match_js(app, vector):
    env = app._signer.sign_view(vector["viewJson"], vector["appId"], vector["timestamp"])
    assert env.payload == vector["viewPayload"]


def test_view_signature_matches_js(app, vector):
    env = app._signer.sign_view(vector["viewJson"], vector["appId"], vector["timestamp"])
    assert env.signature == vector["viewSignature"]


def test_python_verifies_js_view_signature(vector):
    assert (
        YeriaApp.verify_signature(
            vector["publicKey"], vector["viewPayload"], vector["viewSignature"]
        )
        is True
    )


def test_notification_signature_matches_js(app, vector):
    # No link -> JS omits the field entirely; Python must too (not "link":null).
    note = Notification("u1", "Title", "Body")
    signed = app._signer.sign_notification(note, vector["appId"], vector["timestamp"])
    assert signed.signature == vector["noteSignature"]


def test_dev_notification_signature_matches_js(app, vector):
    """Une notification emise depuis un point de developpement.

    Le selecteur `devKeyId` entre dans la charge SIGNEE, en derniere position.
    L'ordre des cles fait partie des octets signes : si Python l'inserait
    ailleurs, la signature differerait de celle de JS et le backend refuserait
    la notification — ce que rien d'autre ne rattraperait avant la production.
    """
    note = Notification("u1", "Title", "Body")
    signed = app._signer.sign_notification(
        note, vector["appId"], vector["timestamp"], vector["devKeyId"]
    )
    assert signed.signature == vector["noteDevSignature"]
    assert signed.dev_key_id == vector["devKeyId"]


def test_rotate_key_refused_in_dev_mode():
    """La rotation ne part pas d'un poste de developpement.

    Le serveur refuse une enveloppe portant `devKeyId`, mais l'enveloppe de
    rotation n'en met pas : la garde serveur ne se declencherait jamais depuis
    ce client. Un deploiement configure en developpement qui detiendrait par
    ailleurs la cle de production pourrait donc faire tourner la cle du service.
    Le refus est donc LOCAL.
    """
    import pytest
    from yeriasdk import YeriaApp, YeriaAppConfig
    from yeriasdk.errors import ConfigurationError

    app = YeriaApp(YeriaAppConfig(
        app_id="s", base_url="http://x", dev_key_id="devkey_abc"
    ))
    # Le refus doit tomber AVANT tout reseau et avant tout usage des cles :
    # deux chaines non vides suffisent donc a le declencher.
    with pytest.raises(ConfigurationError, match="production"):
        app.rotate_key("http://x", "s", {
            "privateKey": "-----BEGIN PRIVATE KEY-----x-----END PRIVATE KEY-----",
            "publicKey": "-----BEGIN PUBLIC KEY-----x-----END PUBLIC KEY-----",
        })


def test_empty_dev_key_id_signs_like_production(app, vector):
    """Une chaine vide n'est pas un selecteur.

    JS n'ajoute la cle que si elle est non vide, et le backend reconstruit la
    charge avec la meme condition. Si Python signait `devKeyId: ""`, il signerait
    quatre cles la ou le serveur en verifie trois : toutes ses notifications
    echoueraient, et seulement les siennes. Le cas arrive des qu'une variable
    d'environnement est definie mais vide.
    """
    note = Notification("u1", "Title", "Body")
    signed = app._signer.sign_notification(note, vector["appId"], vector["timestamp"], "")
    assert signed.signature == vector["noteSignature"]
    assert signed.dev_key_id is None


def test_accented_notification_signature_matches_js(app, vector):
    """Le backend reconstruit la charge utile d'une notification avec
    `JSON.stringify` avant d'en verifier la signature : un titre en francais
    signe par Python doit produire les memes octets que JS. `json.dumps`
    echappait le non-ASCII, donc la verification echouait."""
    note = Notification("u1", "Réservation confirmée ☕", "Votre créneau du 5 à 9 h — merci !")
    signed = app._signer.sign_notification(note, vector["appId"], vector["timestamp"])
    assert signed.signature == vector["noteAccentSignature"]


def test_branding_bytes_and_signature_match_js(app, vector):
    # Same scrambled input as the generator: the normalized object must
    # serialize to the same bytes and a view carrying it must sign the same.
    from yeriasdk.core.yeria_app import _normalize_branding

    branding = _normalize_branding(vector["brandingInput"])
    assert json.dumps(branding, separators=(",", ":")) == vector["brandingBytes"]

    view = {**vector["floatViewJson"], "branding": branding}
    env = app._signer.sign_view(view, vector["appId"], vector["timestamp"])
    assert env.payload == vector["brandedPayload"]
    assert env.signature == vector["brandedSignature"]


def test_boundary_float_payload_bytes_match_js(app, vector):
    """`1.0`, `1e-7`, `1e21`, `-0.0` : Python les ecrivait `1.0`, `1e-07`,
    `1e+21`, `-0.0` la ou JS ecrit `1`, `1e-7`, `1e+21`, `0`. Une latitude
    ronde suffisait a faire diverger la signature des deux SDK."""
    env = app._signer.sign_view(vector["floatViewJson"], vector["appId"], vector["timestamp"])
    assert env.payload == vector["floatPayload"]
    assert env.signature == vector["floatSignature"]
