"""
Cross-SDK structural parity: a view built with the Python SDK must produce the
same JSON as the equivalent view built with the JS SDK, so the Python output is
transparent to the mobile renderer (same keys, same shape, no stray nulls).

The golden views live in tests/fixtures/js_parity_vector.json under
`structuralViews`, generated by the built JS SDK (js/scripts/gen-parity-vector.js).
Each test here rebuilds the same view with the equivalent Python fluent calls
and asserts structural equality, ignoring:
  * metadata.createdAt   — a per-build timestamp
  * key order            — irrelevant to a JSON consumer
  * trailing whitespace on rendered-markdown HTML — the JS and Python markdown
    libraries differ only by a trailing "\\n", which is insignificant to any
    HTML renderer.

Keep the builder calls in sync with the JS generator. Refresh the fixture with
`npm run gen:parity-vector` after any builder/serialization change.
"""

import json
import os

import pytest

from yeriasdk import YeriaApp, YeriaAppConfig, YeriaUI

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "js_parity_vector.json")


@pytest.fixture(scope="module")
def golden():
    with open(FIXTURE) as fh:
        return json.load(fh)["structuralViews"]


@pytest.fixture(scope="module")
def ui():
    return YeriaUI


def _normalize(obj):
    """Deep-sort keys and neutralize the known-volatile / insignificant fields."""
    if isinstance(obj, dict):
        out = {}
        for k in sorted(obj):
            v = obj[k]
            if k == "createdAt":
                v = "<TS>"
            elif k == "content" and isinstance(v, str):
                # rendered-markdown HTML: trailing whitespace is insignificant
                v = v.rstrip()
            out[k] = _normalize(v)
        return out
    if isinstance(obj, list):
        return [_normalize(v) for v in obj]
    return obj


def _build(ui, name):
    if name == "reader":
        return (
            ui.create_reader_view("rd", "Reader").set_intro("hi")
            .add_paragraph("para").add_subtitle("sub").add_markdown("**b**")
            .add_link("Go", "/x").add_separator().to_json()
        )
    if name == "actionlist":
        return (
            ui.create_action_list_view("al", "Actions").set_intro("pick")
            .add_action("/a", "Alpha", "Do A").add_action("/b", "Beta").to_json()
        )
    if name == "actiongrid":
        return (
            ui.create_action_grid_view("ag", "Grid").set_columns(3)
            .add_action("/a", "Alpha").add_action("/b", "Beta").to_json()
        )
    if name == "card":
        return (
            ui.create_card_view("cd", "Card").set_subtitle("sub").set_description("desc")
            .add_stat("Views", "42").add_action("/open", "Open").to_json()
        )
    if name == "timeline":
        return ui.create_timeline_view("tl", "Timeline").add_event("Started", "2026-01-01", "desc").to_json()
    if name == "formval":
        return (
            ui.create_form_view("fv", "F")
            .add_select_field("g", "G", True, [{"value": "m", "label": "M"}, {"value": "f", "label": "F"}])
            .set_field_value("g", "m").to_json()
        )
    raise AssertionError(f"unknown view {name}")


@pytest.mark.parametrize("name", ["reader", "actionlist", "actiongrid", "card", "timeline", "formval"])
def test_view_structurally_matches_js(ui, golden, name):
    py = _normalize(_build(ui, name))
    js = _normalize(golden[name])
    assert py == js
