"""
Cross-SDK parity: the Python SDK must produce byte-for-byte identical signed
output to the JS SDK.

The golden vector (tests/fixtures/js_parity_vector.json) is generated by the
*built JS SDK* — see js/scripts/gen-parity-vector.js. These tests re-sign the
same inputs with the same key at the same fixed timestamp and assert the
Python bytes + Ed25519 signatures match exactly, and that Python verifies the
JS-produced signatures. This is what guarantees notifications / key rotation /
views signed by either SDK are accepted by the same backend and renderer.

Run `node js/scripts/gen-parity-vector.js` to refresh after a JS signing change.
"""

import json
import os

import pytest

from yeriasdk import YeriaApp, YeriaAppConfig, Notification

FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "js_parity_vector.json")


@pytest.fixture(scope="module")
def vector():
    with open(FIXTURE) as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def app(vector):
    return YeriaApp(
        YeriaAppConfig(
            app_id=vector["appId"],
            private_key=vector["privateKey"],
            public_key=vector["publicKey"],
        )
    )


def test_view_payload_bytes_match_js(app, vector):
    env = app._signer.sign_view(vector["viewJson"], vector["appId"], vector["timestamp"])
    assert env.payload == vector["viewPayload"]


def test_view_signature_matches_js(app, vector):
    env = app._signer.sign_view(vector["viewJson"], vector["appId"], vector["timestamp"])
    assert env.signature == vector["viewSignature"]


def test_python_verifies_js_view_signature(vector):
    assert (
        YeriaApp.verify_signature(
            vector["publicKey"], vector["viewPayload"], vector["viewSignature"]
        )
        is True
    )


def test_notification_signature_matches_js(app, vector):
    # No link -> JS omits the field entirely; Python must too (not "link":null).
    note = Notification("u1", "Title", "Body")
    signed = app._signer.sign_notification(note, vector["appId"], vector["timestamp"])
    assert signed.signature == vector["noteSignature"]
